[package]
name = "bookmark-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bookmark-library = { path = "../library" }
clap = { version = "4.0.29", features = ["derive"] }
iced = "0.6"
