[package]
name = "bookmark-library"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
bookmark-storage = { path = "../storage" }
bookmark-command = { path = "../command" }
aho-corasick = "0.7.20"
regex = "1.7.0"
paste = "1.0.9"
thiserror = "1.0.38"
