[package]
name = "bookmark-library"
version = "0.1.0"
edition = "2021"

[dependencies]
bookmark-storage = { path = "../storage" }
bookmark-command = { path = "../command" }
aho-corasick = "0.7.20"
regex = "1.7.0"
paste = "1.0.9"
thiserror = "1.0.38"
once_cell = "1.17.0"
either = "1.8.0"
parking_lot = "0.12.1"
