[package]
name = "bookmark-library"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
bookmark-derive = {path = "../derive"}
bookmark-storage = {path = "../storage"}
aho-corasick = "0.7.20"
regex = "1.7.0"
